branch-defaults:
  main:
    environment: Rieserver-java17
deploy:
  artifact: target/rie-server-0.0.1-SNAPSHOT.zip
environment-defaults:
  Rieserver-env:
    branch: null
    repository: null
  Rieserver-java17:
    branch: null
    repository: null
global:
  application_name: rie-server
  default_ec2_keyname: null
  default_platform: Corretto 17 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
